# CLASE 03 (REPASO)

### {Sistema de ecuaciones con 3 incógnitas}

 Resuelve el siguiente sistema usando la forma matricial $AX = B$:  
$
    \begin{cases}
    x + y + z = 6 \\
    2x - y + 3z = 14 \\
    x + 4y - z = 2
    \end{cases}
$

### Transformación lineal

Considera la matriz de rotación en el plano de ángulo $\theta = \frac{\pi}{2}$:

$
    R = 
    \begin{bmatrix}
    \cos \theta & -\sin \theta \\
    \sin \theta & \cos \theta
    \end{bmatrix}
    $
    Aplica la transformación a los vectores
    $
    v_1 = 
    \begin{bmatrix}
    1 \\
    0
    \end{bmatrix}, \quad
    v_2 = 
    \begin{bmatrix}
    0 \\
    1
    \end{bmatrix}
$
    y representa gráficamente el resultado.



In [2]:
import numpy as np

In [15]:
X = np.array([[1,1,1],[2,-1,3],[1,4,-1]])
b = np.array([6,14,2])
x1,x2,x3 = np.linalg.solve(X,b) # destructurar

In [16]:
print(f"{x1},{x2},{x3}")

4.0,0.0,2.0


In [18]:
np.linalg.det(X)

2.9999999999999996

In [20]:
np.linalg.inv(X)

array([[-3.66666667,  1.66666667,  1.33333333],
       [ 1.66666667, -0.66666667, -0.33333333],
       [ 3.        , -1.        , -1.        ]])

In [27]:
X = np.array([[1,1],[2,2]])
np.linalg.det(X)

0.0

In [32]:
sin_pi2 = np.sin(np.pi/2)
cos_pi2 = np.cos(np.pi/2)

In [42]:
R = np.array([[cos_pi2,-sin_pi2],[sin_pi2,cos_pi2]])
R

array([[ 6.123234e-17, -1.000000e+00],
       [ 1.000000e+00,  6.123234e-17]])

In [35]:
v1 = np.array([1,0])

In [39]:
v1R = np.dot(R,v1) # v1 @ R

In [43]:
v1R

array([6.123234e-17, 1.000000e+00])