# Numpy
Es una librería (una librería es un conjunto de funciones, clases, propiedades, etc) que resuelven problemas determinados.

que sirve principalmente para trabajar con arrays (vectores) y matrices multidimensionales (tensores) y realizar sobre ellos operaciones matemáticas de manera eficiente. Además nos provee muchísimas funciones de matemática como raíz cuadrada, funciones trigonometricas, exponenciales, etc.

NumPy es más rápido que las listas de Python porque está escrito en C y Fortran optimizados para operaciones numéricas. Esto minimiza la sobrecarga de los bucles de Python al realizar cálculos directamente en matrices.

Permite crear y manipular estructuras de datos numéricas mucho más rápidas y compactas que las listas / arrays de Python.
Operaciones vectorizadas
Funciones matemáticas avanzadas
Tenemos distintos mecanísmos para crear arrays en Numpy

Convertirlos de una estructura existente en Python (listas y tuplas)
Creación desde Numpy (arange, ones, zeros, etc)
Joineando o mutando arrays existentes
### ¿Cómo se usa?

```python
    import numpy
    import numpy as np # convención por comunidad
    import numpy as libreria_para_resolver_problemas
```

In [ ]:
pip3 install numpy

In [17]:
import numpy as np

In [118]:
a0 = [1,2,3]
a1 = numpy.array([1.2,2,3,4])

Antes de arrancar, vamos a aclarar algunos conceptos

# Vectores
Lo podemos atacar desde el punto de vista informatico que son elementos contiguos en la memoria, desde el punto de vista físico que es un segmento orientado de recta o bien desde el matemático que es: un vector es un elemento de un espacio vectorial (cerrado bajo sumas entre elemento de ese espacio y cerrado bajo multiplicaciones por un escalar) en este caso vamos a estar trabajando con el típico espacio vectorial (R^n, + , R , *) que es un EV definido sobre el cuerpo de los reales.

Un polinomio es un elemento de un EV.

# Matrices
Son colecciones de numeros (pueden ser reales, complejos, etc) es un arreglo de filas y columnas (pueden ser rectangulares, cuadradas) 
En una matriz se puede condensar información (pueden representar TL's, sistemas de ecuaciones, etc) aa priori fue nomenclatura pero rápidamente se le dio una estructura a esto.

# Tensores

Un tensor es la generalización de lo que acabamos de explicar. Particularmente un escalar es un tensor de orden 0, un vector es un tensor de orden 1, etc. Los tensores se usan mucho en física y matemáticas por ejemplo, para representar la métrica, el tensor de tensiones en mecánica, el tensor energía-momento en relatividad, etc.

En machine learning e IA podemos ver a los tensores como una matriz multidimensional que sirve para guardar información en un espacio de m1xm2xm3x...mn características (ejemplo imagen rgb)

In [10]:
a1

array([1.2, 2. , 3. , 4. ])

In [13]:
# a1 es un objeto de la clase array -> tiene propiedades
a1.ndim # 1 dim ya que es una coleccion de puntos sobre la recta real
a1.shape # cantidad de elementos

(4,)

In [19]:
a2 = np.array([1,2,3,300], dtype=np.int8) # int8 permite hasta numeros de 2^8 (8 bits) (-128 a 127)

/var/folders/qq/wnxyff6j1270wjjsbs6zgkgc0000gp/T/ipykernel_98276/1439646679.py:1: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of 300 to int8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)
will give the desired result (the cast overflows).
  a2 = np.array([1,2,3,300], dtype=np.int8) # int8 permite hasta numeros de 2^8 (8 bits) (-128 a 127)


In [20]:
a2

array([ 1,  2,  3, 44], dtype=int8)

In [23]:
m1 = np.array([[1,2,3],[4,5,6]])
m1

array([[1, 2, 3],
       [4, 5, 6]])

In [25]:
m1.shape # tupla (filas,columnas)

(2, 3)

In [26]:
m1.ndim

2

In [31]:
m2 = np.array([[[1,2],[3,4],[5,6],[7,8]]])
m2.ndim

3

Forma de crear arrays, matrices, etc
```python
    arr = np.array([1,2,3])
    arr.ndim # dimensiones
    arr.shape # (filas,columnas,etc)
    m1 = np.array([[1,2,3],[4,5,6]])
    # linspace
    np.linspace(start,stop, step)
    vec = np.linspace(1,4,100)
    np.arange(10) # crea un vector del 0 al 9 espaciando de un elemento
    np.arange(1,11,2) # crea un vector del 0 al 9 espaciando de un elemento
```

## Métodos de numpy

```python
    np.mean(w_z)
    np.std(w_z)
    np.max(w_z)
```

In [36]:
vec = np.linspace(1,4,100)

In [38]:
vec2 = np.arange(10)
vec2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
vec3 = np.arange(1,11,2)

In [45]:
vec3

array([1, 3, 5, 7, 9])

In [46]:
vec3.shape

(5,)

# Matrices

In [48]:
m1 = np.diag([1,2])

In [50]:
m1

array([[1, 0],
       [0, 2]])

In [52]:
m2 = np.diag([1,2,3])

In [53]:
m2

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [54]:
m3 = np.diag([1,2,3],1)
m3

array([[0, 1, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 3],
       [0, 0, 0, 0]])

In [59]:
m4 = np.zeros((2,3), dtype=int)

In [61]:
m4

array([[0, 0, 0],
       [0, 0, 0]])

In [62]:
m5 = np.zeros((2,3,2), dtype=int)
m5

array([[[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0]]])

In [64]:
# Queremos sumar dos vectores
u = np.array([3,2],dtype=float)
v = np.array([5,0], dtype=float)

In [66]:
u+v

array([8., 2.])

In [69]:
m1 = np.diag((1,2))
m2 = np.array([[2,3],[8,11]])

In [71]:
m1 + m2

array([[ 3,  3],
       [ 8, 13]])

In [77]:
w = np.arange(1,5,1)
z = np.array([1,10,20,30])
w_z = w+z

In [80]:
np.mean(w_z)
np.std(w_z)
np.max(w_z)

34

In [81]:
m3 = 5*m1
m3

array([[ 5,  0],
       [ 0, 10]])

### Producto de matrices

M1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
G = np.array([[1],[2],[3]]

In [83]:
M1 = np.array([[1,2,3],[4,5,6],[7,8,9]]) # 3X3
G = np.array([[1],[2],[3]]) # 3X1

In [85]:
M1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [87]:
H = np.dot(M1,G)
H

array([[14],
       [32],
       [50]])

## Ejercicios de aplicacion

### Suma de matrices

Crea dos matrices de tamaño $3 \times 3$ con números aleatorios $1$ al $9$ y realiza la suma entre ellas.  
$
A + B
$

### Producto elemento a elemento

Genera dos matrices $2 \times 2$ con números aleatorios enteros entre $1$ y $10$, y multiplícalas elemento a elemento.  
    
$C = A \odot B$


### Producto matricial

Crea una matriz $2 \times 3$ y otra $3 \times 2$. Haz el producto matricial y verifica el tamaño del resultado.  
    
$
    C = A \times B
$

### Matriz inversa

Calcula la inversa de la siguiente matriz:
$
    A = 
    \begin{bmatrix}
    4 & 7 \\
    2 & 6
    \end{bmatrix}
$

### Verificación de inversa

Multiplica la matriz anterior por su inversa y demuestra que se obtiene la identidad:

$
    A \cdot A^{-1} = I
$

### Ejercicio aplicado (sistema de ecuaciones)}  

Resuelve el sistema de ecuaciones lineales utilizando matrices:
$
    \begin{cases}
    2x + y = 5 \\
    x + 3y = 7
    \end{cases}
$

### {Sistema de ecuaciones con 3 incógnitas}

 Resuelve el siguiente sistema usando la forma matricial $AX = B$:  
$
    \begin{cases}
    x + y + z = 6 \\
    2x - y + 3z = 14 \\
    x + 4y - z = 2
    \end{cases}
$

### Transformación lineal

Considera la matriz de rotación en el plano de ángulo $\theta = \frac{\pi}{4}$:

$
    R = 
    \begin{bmatrix}
    \cos \theta & -\sin \theta \\
    \sin \theta & \cos \theta
    \end{bmatrix}
    $
    Aplica la transformación a los vectores
    $
    v_1 = 
    \begin{bmatrix}
    1 \\
    0
    \end{bmatrix}, \quad
    v_2 = 
    \begin{bmatrix}
    0 \\
    1
    \end{bmatrix}
$
    y representa gráficamente el resultado.

### Autovalores y autovectores

Calcula los autovalores y autovectores de la matriz:
    $
    A =
    \begin{bmatrix}
    2 & 1 \\
    1 & 2
    \end{bmatrix}
    $
    e interpreta el significado geométrico de los autovectores.


Crear 2 matrices de 3x3 con numeros aleatorios entre 1 y 9 y realizar la suma de estas matrices (A+B)
```python
    A = np.random.randint((1,9,(3,3))
    B = np.random.randing((1,9,(3,3))
```

In [90]:
A = np.array([[1,2,3],[4,4,3],[1,9,6]])
B = np.array([[1,2,3],[4,4,3],[1,9,6]])
A+B

array([[ 2,  4,  6],
       [ 8,  8,  6],
       [ 2, 18, 12]])

In [94]:
A_1 = np.random.randint(1,9,(3,3))
B_1 = np.random.randint(1,9,(3,3))

In [117]:
A_1 + B_1

array([[10,  3, 12],
       [10,  5,  4],
       [11,  3, 13]])

### Producto elemento a elemento

Genera dos matrices $2 \times 2$ con números aleatorios enteros entre $1$ y $10$, y multiplícalas elemento a elemento.  
    
$C = A \odot B$

In [104]:
A = np.random.randint(1,10,(2,2))
B = np.random.randint(1,10,(2,2))

In [108]:
C = np.dot(A,B) # no es conmutativa respecto al producto de matrices
C = A @ B
C

array([[31, 51],
       [44, 78]])

In [111]:
D = np.array([[4,7],[2,6]])
D.ndim
inversa_D = np.linalg.inv(D)
inversa_D

array([[ 0.6, -0.7],
       [-0.2,  0.4]])

$
I = A^{-1} * A
$

In [113]:
D @ inversa_D

array([[ 1.00000000e+00, -1.11022302e-16],
       [ 1.11022302e-16,  1.00000000e+00]])

### Ejercicio aplicado (sistema de ecuaciones)}  

Resuelve el sistema de ecuaciones lineales utilizando matrices:
$
    \begin{cases}
    2x + y = 5 \\
    x + 3y = 7
    \end{cases}
$

$A * \vec{x} = \vec{b}$

In [115]:
A = np.array([[2,1],[1,3]])
b = np.array([5,7])

In [116]:
np.linalg.solve(A,b)

array([1.6, 1.8])