### Ejercicios de funciones trigonométricas, logarítmicas y exponenciales}

Guia de funciones: https://numpy.org/doc/2.2/reference/generated/numpy.sin.html
- Seno y coseno de un ángulo

Calcula los valores de $\sin(\theta)$ y $\cos(\theta)$ para  
$
\theta = \frac{\pi}{6}, \quad \frac{\pi}{4}, \quad \frac{\pi}{3}.
$

Verifica que se cumple la identidad trigonométrica:  
$
    \sin^2(\theta) + \cos^2(\theta) = 1
$

### {Tangente y su relación}

Para los mismos valores de $\theta$, calcula la tangente usando:  
$
    \tan(\theta) = \frac{\sin(\theta)}{\cos(\theta)}
$
y compáralo con el resultado obtenido mediante la función $\tan

### Logaritmo natural y logaritmo en base 10}

Calcula:  

$
    \ln(1), \quad \ln(e), \quad \ln(10)
$
y  
$
    \log_{10}(1), \quad \log_{10}(10), \quad \log_{10}(100).
$

### Exponencial y crecimiento

Evalúa la función exponencial:  
$
    f(x) = e^x
$

para $x = -2, -1, 0, 1, 2$ y representa los valores en una tabla.

### Combinación de funciones
Calcula el valor de la siguiente expresión para $x = 1, 2, 3$:  
$
    g(x) = e^x \cdot \sin(x) + \ln(x+1)
$



In [1]:
# calcular el sin pi/6
import numpy as np

In [3]:
np.sin(np.pi/6)

0.49999999999999994

In [5]:
thetas = np.array([np.pi/6,np.pi/4, np.pi/3, np.pi/2, np.pi])
thetas

array([0.52359878, 0.78539816, 1.04719755, 1.57079633, 3.14159265])

In [7]:
sins = np.sin(thetas)

In [10]:
cos = np.cos(thetas)
cos

array([ 8.66025404e-01,  7.07106781e-01,  5.00000000e-01,  6.12323400e-17,
       -1.00000000e+00])

In [11]:
np.tan(thetas)

array([ 5.77350269e-01,  1.00000000e+00,  1.73205081e+00,  1.63312394e+16,
       -1.22464680e-16])

In [13]:
tan = np.sin(thetas)/np.cos(thetas)
tan

array([ 5.77350269e-01,  1.00000000e+00,  1.73205081e+00,  1.63312394e+16,
       -1.22464680e-16])

In [19]:
# verificar que se cumple la identidad trigonométrica sin^2 + cos^2 = 1
sin2cos2= sins**2 + cos**2
sin2cos2

array([1., 1., 1., 1., 1.])

In [21]:
np.linalg.norm(sin2cos2)

2.23606797749979

Calcula:  

$
    \ln(1), \quad \ln(e), \quad \ln(10)
$
y  
$
    \log_{10}(1), \quad \log_{10}(10), \quad \log_{10}(100).
$


In [24]:
x = np.array([1,np.e,10])
np.log(x) # log -> log natural

array([0.        , 1.        , 2.30258509])

In [27]:
x2 = np.array([1,10,10**2])
np.log

<ufunc 'log'>

### Exponencial y crecimiento

Evalúa la función exponencial:  
$
    f(x) = e^x
$

para $x = -2, -1, 0, 1, 2$ y representa los valores en una tabla.

### Combinación de funciones
Calcula el valor de la siguiente expresión para $x = 1, 2, 3$:  
$
    g(x) = e^x \cdot \sin(x) + \ln(x+1)
$


In [37]:
x = np.array([-2,-1,0,1,2])
x2 = np.linspace(-2,2,10)
np.exp(x2)

array([0.13533528, 0.21107209, 0.32919299, 0.51341712, 0.8007374 ,
       1.24884887, 1.94773404, 3.03773178, 4.73771786, 7.3890561 ])

In [38]:
x = 1

In [40]:
g = np.exp(x)*np.sin(x) + np.log(x+1)
g

2.9805024677387877

In [49]:
def g(x):
    return np.sin(x)*np.exp(x) + np.log(x+1)

### Dominio log(x+1)

$x+1 \gt 0 \implies x > -1 $

$Dm = (-1; \infty)$

In [53]:
x3 = np.linspace(0,5,100)
result = g(x3)

In [54]:
result

array([ 0.00000000e+00,  1.02369791e-01,  2.07784348e-01,  3.16707228e-01,
        4.29572307e-01,  5.46786518e-01,  6.68731564e-01,  7.95764805e-01,
        9.28219444e-01,  1.06640414e+00,  1.21060211e+00,  1.36106977e+00,
        1.51803502e+00,  1.68169509e+00,  1.85221413e+00,  2.02972041e+00,
        2.21430328e+00,  2.40600981e+00,  2.60484115e+00,  2.81074865e+00,
        3.02362972e+00,  3.24332344e+00,  3.46960593e+00,  3.70218554e+00,
        3.94069775e+00,  4.18469994e+00,  4.43366592e+00,  4.68698036e+00,
        4.94393295e+00,  5.20371251e+00,  5.46540099e+00,  5.72796731e+00,
        5.99026116e+00,  6.25100678e+00,  6.50879672e+00,  6.76208560e+00,
        7.00918396e+00,  7.24825222e+00,  7.47729474e+00,  7.69415415e+00,
        7.89650586e+00,  8.08185295e+00,  8.24752132e+00,  8.39065541e+00,
        8.50821431e+00,  8.59696850e+00,  8.65349724e+00,  8.67418673e+00,
        8.65522901e+00,  8.59262191e+00,  8.48216993e+00,  8.31948632e+00,
        8.09999631e+00,  